### ISSUE TITLE
multiple providers not working as expected

### ISSUE THREAD

**Issue by WladyX** [pier-oliviert/phonebook#23]
i have gcore & desec, gcore is working, but desec is not.
if I create a dnsrecord it should create it on gcore but fail on desec, but it does not, because desec is broken, I think gcore does not even try.
```
❯ kd dnsrecords.se.quencer.io test-pb2
Name:         test-pb2
Namespace:    phonebook
Labels:       argocd.argoproj.io/instance=k8s-blue-cc-phonebook
Annotations:  <none>
API Version:  se.quencer.io/v1alpha1
Kind:         DNSRecord
Metadata:
  Creation Timestamp:  2024-11-02T16:23:55Z
  Finalizers:
    phonebook.se.quencer.io/finalizer
  Generation:        1
  Resource Version:  91968120
  UID:               20028aef-13dc-4a2f-9c2f-99ec95c1853d
Spec:
  Name:         test-pb2
  Record Type:  A
  Targets:
    127.0.0.2
  Ttl:   122
  Zone:  myzone.com
Status:
  Conditions:
    Last Transition Time:  2024-11-02T16:23:55Z
    Reason:                Integration found: gcore
    Status:                Completed
    Type:                  Integration
    Last Transition Time:  2024-11-02T16:23:55Z
    Reason:                PB-DESEC-#0002: Unable to create record -- 405: body: {"detail":"Method \"POST\" not allowed."}
    Status:                Error
    Type:                  Provider
Events:                    <none>
```

**Comment by WladyX** [comment]
or it could be another issue, i saw this in the logs:
```
2024-11-02T18:23:55+02:00	ERROR	Reconciler error	{"controller": "dnsrecord", "controllerGroup": "se.quencer.io", "controllerKind": "DNSRecord", "DNSRecord": {"name":"test-pb2","namespace":"phonebook"}, "namespace": "phonebook", "name": "test-pb2", "reconcileID": "d7d99e05-0570-4adc-93f1-3c682ec43160", "error": "Operation cannot be fulfilled on dnsrecords.se.quencer.io \"test-pb2\": the object has been modified; please apply your changes to the latest version and try again"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:316
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224
```

**Comment by pier-oliviert** [comment]
Thank you for writing this issue. You've hit a few snags along the way and I appreciate your patience. I left a few things opened with regards to the DNSIntegration <-> DNSRecord integration because I wasn't sure how I wanted to approach it.

Right now, if you want to have a proper multiple provider support where errors are correctly propagated, you should create 1 DNSRecord *per integration*:

```yaml
apiVersion: se.quencer.io/v1alpha1
kind: DNSRecord
metadata:
  name: gcore-subdomain
spec:
  zone: myzone.com
  recordType: A
  name: subdomain
  target: 127.0.0.1
  integration: gcore
---
apiVersion: se.quencer.io/v1alpha1
kind: DNSRecord
metadata:
  name: desec-subdomain
spec:
  zone: myzone.com
  recordType: A
  name: subdomain
  target: 127.0.0.1
  integration: desec
```

This way, each record will be isolated and you should also have better error association for each record. This is a temporary use case, I'm currently working on making this much better.

Next version, you'll be able to use it exactly how you wanted to. Each `DNSIntegration` that matches for the zone will have its own `Condition` in the status so each provider will track its own progress.

When a DNSRecord has one of the provider not working, the general status of the DNSRecord will be set to `Degraded` which means one or more DNSIntegration failed to create the DNSRecord.

As for the error `the object has been modified; please apply your changes to the latest version and try again` it should not have any impact for you, this *should* be a benign error messages that happens with every Kubernetes operator. When this error happens, the reconciliation loop restarts and the next time it runs, it uses a fresher copy of the resource so it doesn't have conflict. The solution for it is to use SSA( Server-side apply) but it's a complicated beast and I want to see if I cannot figure a better way to deal with conflicts.

**Comment by WladyX** [comment]
Thank you for all your support and for the detailed explanation!
You are doing all the heavy lifting, I'm just testing & reporting bugs :)
I saw that error on other operators as well, so good to know!
I'll be waiting for desec & the next release since I have many subdomains, and I don't want to duplicate, but still it is good to keep in mind, maybe I'll need to have different records at a later point, maybe add it docs also (if not already).
